<?php
if ($totalCount):
	
	if ($currentPage != 1):?>
		<a href="<?php echo $this->escapeHtml($previousPageUrl); ?>" class="previous o-icon-prev button" aria-label=" <?php echo $this->escapeHtml($this->translate('Previous')); ?>"></a>
		<?php else: ?>
		<span class="previous o-icon-prev button inactive"></span>
		<?php endif; ?>
	
<div class="current-pagination">
    <form method="GET" action="">
        <?php echo $this->queryToHiddenInputs(['page']); 
		echo $this->translate('Page'); ?>
        <input type="text" name="page" id="page-input-top" value="<?php echo $currentPage; ?>" size="4" <?php echo ($pageCount == 1) ? 'readonly' : ''; ?>>
        <span class="page-count"><?php echo sprintf($this->translate('of %s'), $pageCount); ?></span>
    </form>

	<?php
	$from = $offset + 1;
	$to = ($currentPage < $pageCount) ? $offset + $perPage : $totalCount;
	?>
    <span class="row-count"><?php echo sprintf('Items %s–%s of %s', $from, $to, $totalCount); ?></span>
</div>
	
	<?php if ($currentPage < $pageCount): ?>
    <a href="<?php echo $this->escapeHtml($nextPageUrl); ?>" class="next o-icon-next button" aria-label=" <?php echo $this->escapeHtml($this->translate('Next')); ?>"></a>
    <?php else: ?>
    <span class="next o-icon-next button inactive"></span>
    <?php endif; ?>
<?php else: ?>
    <?php echo $this->translate('0 results'); ?>
<?php endif; ?>
</nav>
