<nav class="pagination" role="navigation">
<?php if ($totalCount): ?>
	
	<?php if ($currentPage != 1): ?>
		<?php echo $this->hyperlink('', $previousPageUrl, ['class' => 'previous o-icon-prev button', 'title' => $this->translate('Previous')]); ?>
	<?php else: ?>
		<span class="previous o-icon-prev button inactive"></span>
	<?php endif; ?>
	
<div class="current-pagination">
    <form method="GET" action="">
        <?php echo $this->queryToHiddenInputs(['page']); ?>
		<?= $this->translate('Page'); ?>
        <input type="text" name="page" class="page-input-top" value="<?php echo $currentPage; ?>" size="4" <?php echo ($pageCount == 1) ? 'readonly' : ''; ?>>
        <span class="page-count"><?php echo sprintf($this->translate('of %s'), $pageCount); ?></span>
    </form>

	<?php
	$from = $offset + 1;
	$to = ($currentPage < $pageCount) ? $offset + $perPage : $totalCount;
	?>
    <span class="row-count"><?php echo sprintf($this->translate('%s–%s of %s'), $from, $to, $totalCount); ?></span>
</div>
	
	<?php if ($currentPage < $pageCount): ?>
	<?php echo $this->hyperlink('', $nextPageUrl, ['class' => 'next o-icon-next button', 'title' => $this->translate('Next')]); ?>
    <?php else: ?>
	<span class="next o-icon-next button inactive"></span>
    <?php endif; ?>
<?php else: ?>
    <?php echo $this->translate('0 results'); ?>
<?php endif; ?>
</nav>
