<?php
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
$settings = $this->themeSetting('properties')['letter'];

if(isset($shouldDisplayFront)) { //For item/show view
	$frontTerms = array_flip([$settings['publishedIn']]);
	if(isset($repeatTop) && $repeatTop || !$shouldDisplayFront)
		$frontTerms += array_flip([$settings['sender'], $settings['addressee'], $settings['date']]);
	$values = $shouldDisplayFront
			? array_intersect_key($values, $frontTerms)
			: array_diff_key($values, $frontTerms);
} ?>
<?php foreach ($values as $term => $propertyData): ?>
    <div class="property">
        <h4 class="field-name">
        <?php if ($propertyData['alternate_label']): ?>
        <?php echo $escape($propertyData['alternate_label']); ?>
        <?php else: ?>
        <?php echo $escape($this->translate($propertyData['property']->label())); ?>
        <?php endif; ?>
        <?php if ('term' === $labelInfo): ?>
        <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
        <?php elseif ('vocab' === $labelInfo): ?>
        <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
        <?php endif; ?>
        </h4>
        <div class="values">
        <?php foreach ($propertyData['values'] as $value): ?>
            <?php
            $class = 'value';
            if ('resource' == $value->type()) {
                $valueResource = $value->valueResource();
                $class .= ' resource ' . $escape($valueResource->resourceName());
            } elseif ('uri' == $value->type()) {
                $class .= ' uri';
            }
            ?>
            <div class="<?php echo $class; ?>" lang="<?php echo $escape($value->lang()); ?>">
                <?php if ($language = $value->lang()): ?>
                <span class="language"><?php echo $language; ?></span>
                <?php endif; ?>
                <?php echo $value->asHtml(); ?>
            </div>
        <?php endforeach; ?>
		</div>
    </div>
<?php endforeach; ?>
