<?php
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');

if(isset($itemClass)){
	$biblioTypes = $this->api()->search('search_pages', ['form' => 'Biblio'])
			->getContent()[0]->settings()['form']['resource_classes'];
	
	if(in_array($itemClass, $biblioTypes))
		$itemType = 'biblio';
	else
		$itemType = strtolower(explode(':', $itemClass)[1]);
}
else $itemType = 'default';

$settings = isset($this->themeSetting('properties')[$itemType])
		? $this->themeSetting('properties')[$itemType]
		: $this->themeSetting('properties')['default'];

if(isset($display)) { //For item/show view
	$terms = [];
	switch ($display) {
		case 'other':
		case 'front':
			$terms += array_flip(explode(';', $settings['front']));
			if(isset($repeatTop) && !$repeatTop) break;
		case 'top':
			$terms += array_flip(explode(';', $settings['top']));
			break;
	}

	$values = $display !== 'other'
		? array_intersect_key($values, $terms)
		: array_diff_key($values, $terms);
} ?>
<?php foreach ($values as $term => $propertyData): ?>
    <div class="property">
        <h4 class="field-name">
        <?php if ($propertyData['alternate_label']): ?>
        <?php echo $escape($propertyData['alternate_label']); ?>
        <?php else: ?>
        <?php echo $escape($this->translate($propertyData['property']->label())); ?>
        <?php endif; ?>
        <?php if ('term' === $labelInfo): ?>
        <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
        <?php elseif ('vocab' === $labelInfo): ?>
        <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
        <?php endif; ?>
        </h4>
        <div class="values">
		<?php $valueNumber = 1; ?>
        <?php foreach ($propertyData['values'] as $value): ?>
			<?php
			if($value->lang() //if lang is set
					&& 'fr' !== strtolower($value->lang()) //but not french
					&& in_array('fr', //whereas french exist
							array_map(
									function($v){ return $v->lang(); },
									$propertyData['values']))
			)
				continue; //do not display this value
			?>
            <?php
            $class = 'value';
            if ('resource' == $value->type()) {
                $valueResource = $value->valueResource();
                $class .= ' resource ' . $escape($valueResource->resourceName());
            } elseif ('uri' == $value->type()) {
                $class .= ' uri';
            }
            ?>
            <div class="<?php echo $class; ?>" lang="<?php echo $escape($value->lang()); ?>">
                <?php if ($language = $value->lang()): ?>
                <span class="language">(<?php echo $language; ?>)</span>
                <?php endif; ?>
                <?php echo $value->asHtml(); 
				if($valueNumber++ < count($propertyData['values'])) echo ' ;'; ?>
            </div>
        <?php endforeach; ?>
		</div>
    </div>
<?php endforeach; ?>
