<?php $escape = $this->plugin('escapeHtml');?>
<?php $this->htmlElement('body')->appendAttribute('class', 'item-set resource browse'); ?>

<?php echo $this->pageTitle($this->translate('Item sets'), 2); ?>

<?php echo $this->searchFilters(); ?>
<?php $query = $this->params()->fromQuery(); ?>
<?php echo $this->hyperlink($this->translate('Filter differently'), $this->url(null, ['action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search button']); ?>
<?php echo $this->pagination(); ?>
<?php $this->trigger('view.browse.before'); ?>
<ul class="resource-list">
    <?php foreach ($itemSets as $itemSet): ?>
    <li class="item-set resource">
        <h4><?php echo $itemSet->link($itemSet->displayTitle()); ?></h4>
        <?php if ($description = $itemSet->displayDescription()): ?>
        <div class="description"><?php echo $description; ?></div>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php $this->trigger('view.browse.after'); ?>
<?php echo $this->pagination(); ?>
