<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');
$query = $this->params()->fromQuery();
if (isset($itemSet)):
	$this->htmlElement('body')->appendAttribute('class', 'item-set');
	$query['item_set_id'] = $itemSet->id();
endif;

if (isset($itemSet)):
	echo $this->pageTitle($itemSet->displayTitle(), 2); ?>
   <div class="metadata">
	   <?php echo $itemSet->displayValues(); ?>
   </div>
   <?php echo $this->pageTitle($itemSet->itemCount()." ".$this->translate('Items'), 3);
else:
	echo $this->pageTitle($this->translate('Items'), 2);
endif;

echo $this->searchFilters();
echo $this->pagination(); ?>
<ul class="resource-list">
    <?php foreach ($items as $item): ?>
    <li class="item resource">
        <h4><?php echo $item->link($item->displayTitle()); ?></h4>
		<?php if ($primaryMedia = $item->primaryMedia()): ?>
        <img
            src="<?php echo $escape($primaryMedia->thumbnailUrl('medium')); ?>"
            title="<?php echo $escape($primaryMedia->displayTitle()); ?>"
            alt="<?php echo $escape($primaryMedia->mediaType()); ?> thumbnail"
        >
        <?php endif; ?>
        <?php if ($date = $item->value('dcterms:date')): ?>
        <div class="date"><?php echo $date; ?></div>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php echo $this->pagination(); ?>
<?php $this->trigger('view.browse.after'); ?>
