<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');
$query = $this->params()->fromQuery();
if (isset($itemSet)):
	$this->htmlElement('body')->appendAttribute('class', 'item-set');
	$query['item_set_id'] = $itemSet->id();
endif;

if (isset($itemSet)):
	echo $this->pageTitle($itemSet->displayTitle(), 2); ?>
   <div class="metadata">
	   <?php echo $itemSet->displayValues(); ?>
   </div>
   <?php echo $this->pageTitle($itemSet->itemCount()." ".$this->translate('Items'), 3);
else:
	echo $this->pageTitle($this->translate('Items'), 2);
endif;

$filterBtn=(string) $this->hyperlink($this->translate('Filter'),
			$this->url('site/resource',
				['controller' => 'item', 'action' => 'search'],
				['query' => $query], true),
			['class' => 'advanced-search button']);

echo $this->searchFilters(); ?>
<nav class="pagination" role="navigation">
<?php
echo $filterBtn;
echo $this->pagination(); ?>
<ul class="resource-list">
    <?php foreach ($items as $item): ?>
    <li class="item resource">
        <h4><?php echo $item->link($item->displayTitle()); ?></h4>
		<?php if ($primaryMedia = $item->primaryMedia()): ?>
        <img
            src="<?php echo $escape($primaryMedia->thumbnailUrl('medium')); ?>"
            title="<?php echo $escape($primaryMedia->displayTitle()); ?>"
            alt="<?php echo $escape($primaryMedia->mediaType()); ?> thumbnail"
        >
        <?php endif; ?>
        <?php if ($date = $item->value('dcterms:date')): ?>
				<h5 class="field-name">Date</h5> <div class="date"><?php echo $date; ?></div>
        <?php endif;
			if ($description = $item->value('dcterms:description')): ?>
				<h5 class="field-name">Description</h5> <div class="value description"><?php echo $description; ?></div>
        <?php endif;
			if($incipit = $item->value('dm2e:incipit')): ?>
				<h5 class="field-name">Incipit</h5> <q class="value description"><?php echo $incipit; ?></q>
		<?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<nav class="pagination" role="navigation">
<?=
$filterBtn
.$this->pagination() ?>
<?php $this->trigger('view.browse.after'); ?>
