<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');
$query = $this->params()->fromQuery();
if (isset($itemSet)):
	$this->htmlElement('body')->appendAttribute('class', 'item-set');
	$query['item_set_id'] = $itemSet->id();
endif;
$headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
$bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');
$itemSetShow = isset($itemSet);
$filterBtn=(string) $this->hyperlink($this->translate('Filter'),
			$this->url('site/resource',
				['controller' => 'item', 'action' => 'search'],
				['query' => $query], true),
			['class' => 'advanced-search button']);
?>

<?php if ($itemSetShow): ?>
	<?php echo $this->pageTitle($itemSet->displayTitle(), 2); ?>
   <div class="metadata">
	   <?php echo $itemSet->displayValues(); ?>
   </div>
	<div class="item-set-items">
	<?php echo '<h3>'.$itemSet->itemCount().' '.$escape($this->translate('Items')) . '</h3>'; ?>
<?php else: ?>
	<?php echo $this->pageTitle($this->translate('Items'), 2),
	$filterBtn,
	$this->pagination(); ?>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>
<?php $this->trigger('view.browse.before'); ?>
<ul class="resource-list">
<?php
foreach ($items as $item):
    $heading = $item->value($headingTerm, ['default' => $this->translate('[Untitled]')]);
    $body = $item->value($bodyTerm);
?>
    <li class="item resource">
        <h4><?php echo $item->link($heading); ?></h4>
		<?php echo $item->linkRaw($this->thumbnail($item, 'medium')); ?>
        <?php if ($date = $item->value('dcterms:date')): ?>
				<h5 class="field-name">Date</h5> <div class="date"><?= $date; ?></div>
        <?php endif; ?>
		<?php if ($body): ?>
				<h5 class="field-name">Description</h5> <div class="value description"><?= $body; ?></div>
        <?php endif;
			if($incipit = $item->value('dm2e:incipit')): ?>
				<h5 class="field-name">Incipit</h5> <q class="value description"><?= $incipit; ?></q>
		<?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php echo ($itemSetShow) ? '</div>' : '', $filterBtn; ?>
<?php $this->trigger('view.browse.after'); ?>
<?php echo $this->pagination(); ?>
