<?php 
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$subjects = $item->subjectValues();
$objects = $item->objectValues();
?>

<?php echo $this->pageTitle($item->displayTitle(), 2); ?>

<?php
$hasViewableMedia = false;
foreach ($item->media() as $media)
	$hasViewableMedia = ($hasViewableMedia or $media->hasThumbnails());

if ($hasViewableMedia):
	    echo $this->universalViewer($item, ['class'=>'masked']);
endif;
if($item->media()): ?>
<div id="itemfiles" class="masked"></div>
<div id="itemfiles-nav" class="media-list">
    <?php foreach ($item->media() as $media): ?>
        <a href="<?php echo $media->siteUrl(); ?>" class="media resource chocolat-image">
			<?php if($media->hasThumbnails()): ?>
				<img src="<?php echo $escape($media->thumbnailUrl('medium')); ?>" title="<?php echo $escape($media->displayTitle()); ?>">
			<?php else: ?>
				<div class="media-element">
				<?php echo $escape($media->displayTitle()); ?>
				</div>
			<?php endif; ?>
        </a>
    <?php endforeach; ?>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('#itemfiles-nav a:has("img")').on("click", function(event){
		jQuery('.uv').removeClass('masked');
		jQuery('.uv').show();
		jQuery(document).scrollTop(jQuery('.uv').offset().top);
		event.preventDefault();
	});
});</script>
<?php endif;

echo $item->displayValues();

$itemSets = $item->itemSets();
if (count($itemSets) > 0): ?>
<div class="property">
    <h4><?php echo $this->translate('Item Sets'); ?></h4>
    <?php foreach ($item->itemSets() as $itemSet): ?>
    <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<?php if ($subjects || $objects): ?>
<div id="item-linked" class="section property">
    <h4><?php echo $this->translate('Linked Resources'); ?></h4>
    <div class="value">
    <?php echo $item->displayLinkedResources(); ?>
    </div>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>
