<?php 
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
/* @var $itemMedia Omeka\Api\Representation\MediaRepresentation[] */
$itemMedia = $item->media();
$settings = $this->themeSetting('properties');
$this->headScript()->appendScript(<<<'EOT'
	var wereHidden = false;
	function toggler(){
		$(".advanced_properties").toggle();
		if(wereHidden) $(this).text(" Masquer les autres propriétés")
							.toggleClass('fa-minus-square fa-plus-square');
		else $(this).text(" Afficher les autres propriétés")
					.toggleClass('fa-minus-square fa-plus-square');
		wereHidden = !wereHidden;
	}

	$(document).ready(function() {
		$("#advanced_properties_toggler").click(toggler).trigger("click");
	});
EOT
);

$itemClass = $item->resourceClass() ? $item->resourceClass()->term() : null;

$shouldHaveTranscription = $itemClass //may be NULL
		? in_array($itemClass, explode(';', $settings['transcriptedClasses']))
		: false;
?>

<?php echo $this->pageTitle($item->displayTitle(), 2, $item->displayResourceClassLabel()); ?>

<?php $this->trigger('view.show.before'); ?>
<?php
$transcriptionHasBeenDisplayed = false;
if ($embedMedia && $itemMedia) // Affichage de la transcription
	foreach ($itemMedia as $medium)
		if('HTML' == $medium->ingesterLabel()
				&& stristr($medium->displayTitle(), 'transcription')) {
			$this->headScript()->prependScript(
					'MathJax.Hub.Config({ MMLorHTML: { prefer: { Firefox: "MML" } }  });',
					'text/x-mathjax-config');
			$this->headScript()->appendFile(
					'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML');
			$this->headLink()->appendStylesheet($this->assetUrl('css/latex/LaTeXML.css'));
			$this->headLink()->appendStylesheet($this->assetUrl('css/latex/ltx-amsart.css'));
			$this->headLink()->appendStylesheet($this->assetUrl('css/latex/ltx-amsart-hpp.css'));
			$this->headLink()->appendStylesheet($this->assetUrl('css/latex/ltx-article.css'));
			$this->headLink()->appendStylesheet($this->assetUrl('css/latex/ltx-ulem.css'));
			echo $medium->render();
			$transcriptionHasBeenDisplayed = true;
			break;
		}
if($shouldHaveTranscription && !$transcriptionHasBeenDisplayed) {
	echo '<div>La transcription n’est pas disponible.</div>';
}

//Métadonnées d’entête
echo $item->displayValues(['itemClass'=>$itemClass, 'display'=>'top']);
?>
<div style="width:100%; overflow:hidden; clear:both"></div>
<?php $hasViewableMedia = false;
if($embedMedia && $itemMedia):
	foreach ($itemMedia as $media) {
		if($hasViewableMedia = $media->hasThumbnails()) {
			echo $this->universalViewer($item);
			break;
		}
	} ?>
	<div id="itemfiles-nav" class="media-list">
		<?php foreach ($itemMedia as $medium): ?>
			<?php if(!$medium->hasThumbnails() && !stristr($medium->displayTitle(), 'transcription')): ?>
				<a href="<?php echo $medium->siteUrl(); ?>" class="media resource chocolat-image">
					<div class="media-element">
					<?php echo $escape($medium->displayTitle()); ?>
					</div>
				</a>
			<?php endif; ?>
		<?php endforeach; ?>
	</div>
<?php endif; ?>
<?php echo $item->displayValues(['itemClass'=>$itemClass, 'display'=>'front',
	'repeatTop'=>$hasViewableMedia]); ?>
<div class="property"><a id="advanced_properties_toggler" class="fa fa-minus-square">
		Masquer les autres propriétés</a></div>
<div class="advanced_properties">
	<?= $item->displayValues(['itemClass'=>$itemClass, 'display'=>'other']); ?>
</div>
<div class="property">
	<?php $itemSets = $item->itemSets(); ?>
	<?php if (count($itemSets) > 0): ?>
		<h4><?php echo $this->translate('Item sets'); ?></h4>
		<?php foreach ($item->itemSets() as $itemSet): ?>
		<div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
		<?php endforeach; ?>
	<?php endif; ?>
</div>
<?php if (!$embedMedia && $itemMedia): ?>
<div class="media-list">
    <?php foreach ($itemMedia as $media): ?>
        <?php echo $media->linkPretty(); ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<?php
	$page = $this->params()->fromQuery('page', 1);
	$property = $this->params()->fromQuery('property');
	$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked" class="section property">
    <h3><?php echo $this->translate('Linked resources'); ?></h3>
    <div class="value">
    <?php echo $subjectValues; ?>
    </div>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>
