<?php
use Omeka\Api\Representation\ItemRepresentation;
use Omeka\Api\Representation\ValueRepresentation;
$escape = $this->plugin('escapeHtml');
$link = $this->plugin('hyperlink');
/* @var $resource ItemRepresentation */ 

$author = ($valueCreator = $resource->value("dcterms:creator")) instanceof ValueRepresentation
		? $link($escape($valueCreator->valueResource()->displayTitle()),
				$valueCreator->valueResource()->url(), [])
		: $valueCreator;

$journal = ( ($issueVal = $resource->value('dcterms:isPartOf'))
				instanceof ValueRepresentation
			&& ($journalVal = $issueVal->valueResource()->value('dcterms:isPartOf'))
				instanceof ValueRepresentation
			)
		? $journalVal->valueResource()->displayTitle()
		: '';
?>

<tr class="<?= $resource->resourceName(); ?> resource">
	<td><?= $author ?></td>
	<td><?= $resource->link($resource->value("dcterms:title")); ?></td>
	<td><?= $resource->value("dcterms:issued"); ?></td>
	<td><?= $journal; ?></td>
</tr>