<?php
use Omeka\Api\Representation\ItemRepresentation;
use Omeka\Api\Representation\ValueRepresentation;
$escape = $this->plugin('escapeHtml');
$link = $this->plugin('hyperlink');
$settings = $this->themeSetting('properties')['letter'];
/* @var $resource ItemRepresentation */ 

$sender = ($senderAsVal = $resource->value($settings['sender']))
		instanceof ValueRepresentation
		? $link($escape($senderAsVal->valueResource()->displayTitle()),
				$senderAsVal->valueResource()->url(), [])
		: $senderAsVal;

$recipient = ($recipientAsVal = $resource->value($settings['addressee']))
		instanceof ValueRepresentation
		? $link($escape($recipientAsVal->valueResource()->displayTitle()),
				$recipientAsVal->valueResource()->url(), [])
		: $recipientAsVal;
?>

<tr class="<?= $resource->resourceName(); ?> resource">
	<td><?= $sender ?></td>
	<td><?= $recipient ?></td>
	<td><?= $resource->value($settings['date']); ?></td>
	<td><?= $resource->link($resource->value($settings['incipit'])); ?></td>
</tr>