<?php
use Omeka\Api\Representation\ItemRepresentation;
use Omeka\Api\Representation\ValueRepresentation;
$escape = $this->plugin('escapeHtml');
$settings = $this->themeSetting('properties')['letter'];
/* @var $resource ItemRepresentation */ 

$sender = $resource->value($settings['sender']) instanceof ValueRepresentation
		? $resource->value($settings['sender'])->valueResource()->displayTitle()
		: $resource->value($settings['sender']);
$recipient = $resource->value($settings['addressee']) instanceof ValueRepresentation
		? $resource->value($settings['addressee'])->valueResource()->displayTitle()
		: $resource->value($settings['addressee']);
?>

<tr class="<?= $resource->resourceName(); ?> resource">
	<td><?= $sender ?></td>
	<td><?= $recipient ?></td>
	<td><?= $resource->value($settings['date']); ?></td>
	<td><?= $resource->link($resource->value($settings['incipit'])); ?></td>
    <?php if ($description = $resource->displayDescription()): ?>
        <div class="description">
            <?php echo $description; ?>
        </div>
    <?php endif; ?>
</tr>