<?php $results = $response->getResults($resourceName);
$form=$this->searchForm()->getForm();
switch(get_class($form)){
		case \EhpSearchForm\Form\LetterForm::class :
			$ehpForm = 'letter';
			break;
		case \EhpSearchForm\Form\ReportForm::class :
			$ehpForm = 'report';
			break;
		default:
			$ehpForm = 'biblio';
} ?>
<?php if (!empty($results)): ?>
    <h3><?php echo $title; ?></h3>
    <div class="resource-list"><table>
		<thead><tr>
			<?= $this->partial("search/$ehpForm-list") ?>
		</tr></thead>
		<tbody>
        <?php foreach ($results as $result): ?>
            <?php $resource = $this->api()->read($resourceName, $result['id'])->getContent(); ?>
            <?php echo $this->partial("search/$ehpForm", ['resource' => $resource,
                                                          'site' => $site,
                                                          'tag' => 'div']); ?>
        <?php endforeach; ?>
		</tbody>
	</table></div>
<?php endif; ?>
