<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', 'fr');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
$logo = $this->themeSettingAssetUrl('logo');
if ($logo):
    $title = '<img src="' . $this->escapeHtml($logo) . '">';
endif;
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <header>
			<h1 id="site-title"><a href="<?php echo $site->url(); ?>">
			<?php if ($this->themeSetting('logo')): ?>
			<img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" title="Logo">
			<?php else: echo $this->pageTitle($site->title()); endif;?>
			</a></h1>
			<div id="search-form">
				<form action="<?php echo $this->escapeHtml($this->url('site/resource', ['controller' => 'item','action' => 'browse'], true)); ?>">
					<?php $searchValue = isset($_GET['search']) ? $_GET['search'] : ''; ?>
					<input type="text" name="search" value="<?php echo $escape($searchValue); ?>" placeholder="<?php echo $this->translate('Search items'); ?>">
					<button type="submit"><?php echo $this->translate('Search'); ?></button>
				</form>
				<?php echo $this->hyperlink($this->translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], [], true), ['class' => 'advanced-search']); ?>
			</div>

            <nav id="navigation">
            <?php
            echo $site->publicNav()->menu()->renderMenu(null, [
                'maxDepth' => 0//$this->themeSetting('nav_depth') - 1
            ]);
            ?>
            </nav>
        </header>
        <div id="content" role="main">
            <?php echo $this->content; ?>
        </div>
        <footer>
            <?php if ($footerContent = $this->themeSetting('footer')): ?>
            <?php echo $footerContent; ?>
            <?php else: ?>
                <?php echo $this->translate('Powered by Omeka S'); ?>
            <?php endif; ?>
        </footer>
    </body>
</html>
